###############################################################################
#
# Makefile for a Assembler.py, project 6
# assembler for the hack language
#
###############################################################################

# **** Beginning of the actual Makefile ****
all:
	chmod 777 Assembler